version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pawfect_learning_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pawfect_learning_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - pawfect_network

  adminer:
    image: adminer
    container_name: pawfect_learning_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - pawfect_network

networks:
  pawfect_network:
    driver: bridge

volumes:
  mysql_data: